# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchline < Formula
  desc "Streamline OpenCode plugin updates."
  homepage "https://github.com/AksharP5/Patchline"
  version "1.1.2"

  on_macos do
    on_intel do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.2/patchline_1.1.2_darwin_amd64.tar.gz"
      sha256 "6d5478e33d05688049d0311c5aa724037377c5f5fef83147d14ce93209e1832d"

      def install
        bin.install "patchline"
      end
    end
    on_arm do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.2/patchline_1.1.2_darwin_arm64.tar.gz"
      sha256 "10cd2cf2d22a1dd79fe05a3def1c9ea13cd74ba51b1088b6b54ea7dc83156d3b"

      def install
        bin.install "patchline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.2/patchline_1.1.2_linux_amd64.tar.gz"
        sha256 "512ede106aa02d2bdb5cbe7f63fae4386b255c337958dc66102882274b17705c"

        def install
          bin.install "patchline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.2/patchline_1.1.2_linux_arm64.tar.gz"
        sha256 "44e24ed1d3f9701ae0112bd550d806e26e0134c4f3599a3712f4f30e1f6ff132"

        def install
          bin.install "patchline"
        end
      end
    end
  end
end
