# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchline < Formula
  desc "Streamline OpenCode plugin updates."
  homepage "https://github.com/AksharP5/Patchline"
  version "1.1.6"

  on_macos do
    on_intel do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.6/patchline_1.1.6_darwin_amd64.tar.gz"
      sha256 "eb38a5a43cbb91b3e5799bff399b801d1e710c018b6f303ee4a62edc5b7b5109"

      def install
        bin.install "patchline"
      end
    end
    on_arm do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.6/patchline_1.1.6_darwin_arm64.tar.gz"
      sha256 "0096dba467a377a0cda423475f88e27559ea008f5cd74c3aaeb49e74633d22f8"

      def install
        bin.install "patchline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.6/patchline_1.1.6_linux_amd64.tar.gz"
        sha256 "1b9d42e32e8acc09a35e07916f369047111e2efcec833da5f6e884d1bbd54ca4"

        def install
          bin.install "patchline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.6/patchline_1.1.6_linux_arm64.tar.gz"
        sha256 "c62c417879a5ed8e4f2c7aa4aff818fd559b174b27303c5a1bdfd8a223f87120"

        def install
          bin.install "patchline"
        end
      end
    end
  end
end
